-- ============================================================================
-- SCRIPT PARA CREAR TODOS LOS TRIGGERS DE AEROLINEA4.TICKETS
-- Ejecutar en DBeaver conectado al esquema AEROLINEA4
-- ============================================================================

-- PASO 1: Eliminar triggers duplicados si existen
BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER AEROLINEA4.TRG_TICKETS_DECREMENT_SEATS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- PASO 2: CREAR TRG_TICKETS_AD_RESTORE (restaurar asientos al eliminar)
CREATE OR REPLACE TRIGGER AEROLINEA4.TRG_TICKETS_AD_RESTORE
AFTER DELETE ON AEROLINEA4.TICKETS
FOR EACH ROW
DECLARE
  v_qty NUMBER := NVL(:OLD.QUANTITY, 1);
BEGIN
  UPDATE AEROLINEA4.FLIGHTS
     SET AVAILABLE_SEATS = NVL(AVAILABLE_SEATS,0) + v_qty,
         UPDATED_AT      = TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH24:MI:SS')
   WHERE ID_FLIGHT = :OLD.FLIGHT_ID;

  BEGIN
    UPDATE AEROLINEA4.FLIGHT_INVENTORY
       SET SOLD_SEATS      = GREATEST(0, NVL(SOLD_SEATS,0) - v_qty),
           AVAILABLE_SEATS = GREATEST(
                               0,
                               NVL(TOTAL_SEATS,0) - NVL(RESERVED_SEATS,0) - GREATEST(0, NVL(SOLD_SEATS,0) - v_qty)
                             ),
           UPDATED_AT      = SYSTIMESTAMP
     WHERE FLIGHT_ID     = :OLD.FLIGHT_ID
       AND SEAT_CATEGORY = :OLD.SEAT_CATEGORY;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

-- PASO 3: CREAR TRG_TICKETS_AI_DECREMENT (descontar asientos al insertar)
CREATE OR REPLACE TRIGGER AEROLINEA4.TRG_TICKETS_AI_DECREMENT
AFTER INSERT ON AEROLINEA4.TICKETS
FOR EACH ROW
DECLARE
  v_qty NUMBER := NVL(:NEW.QUANTITY, 1);
BEGIN
  -- Global del vuelo (indiferente a categoría)
  UPDATE AEROLINEA4.FLIGHTS
     SET AVAILABLE_SEATS = GREATEST(0, NVL(AVAILABLE_SEATS,0) - v_qty),
         UPDATED_AT      = TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH24:MI:SS')
   WHERE ID_FLIGHT = :NEW.FLIGHT_ID;

  -- Inventario por categoría (si existe registro)
  BEGIN
    UPDATE AEROLINEA4.FLIGHT_INVENTORY
       SET SOLD_SEATS      = NVL(SOLD_SEATS,0) + v_qty,
           AVAILABLE_SEATS = GREATEST(
                               0,
                               NVL(TOTAL_SEATS,0) - NVL(RESERVED_SEATS,0) - (NVL(SOLD_SEATS,0) + v_qty)
                             ),
           UPDATED_AT      = SYSTIMESTAMP
     WHERE FLIGHT_ID     = :NEW.FLIGHT_ID
       AND SEAT_CATEGORY = :NEW.SEAT_CATEGORY;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END;
/

-- PASO 4: CREAR TRG_TICKETS_AU_STATUS_RESTORE (restaurar al cancelar)
CREATE OR REPLACE TRIGGER AEROLINEA4.TRG_TICKETS_AU_STATUS_RESTORE
AFTER UPDATE OF STATUS ON AEROLINEA4.TICKETS
FOR EACH ROW
DECLARE
  v_qty NUMBER := NVL(:OLD.QUANTITY, 1);
  FUNCTION is_cancel(new_status VARCHAR2) RETURN NUMBER IS
  BEGIN
    IF new_status IN ('CANCELLED','REFUNDED') THEN RETURN 1; END IF;
    RETURN 0;
  END;
BEGIN
  IF NVL(:OLD.STATUS,'CONFIRMED') IN ('RESERVED','CONFIRMED')
     AND is_cancel(:NEW.STATUS) = 1 THEN

    UPDATE AEROLINEA4.FLIGHTS
       SET AVAILABLE_SEATS = NVL(AVAILABLE_SEATS,0) + v_qty,
           UPDATED_AT      = TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH24:MI:SS')
     WHERE ID_FLIGHT = :OLD.FLIGHT_ID;

    BEGIN
      UPDATE AEROLINEA4.FLIGHT_INVENTORY
         SET SOLD_SEATS      = GREATEST(0, NVL(SOLD_SEATS,0) - v_qty),
             AVAILABLE_SEATS = GREATEST(
                                 0,
                                 NVL(TOTAL_SEATS,0) - NVL(RESERVED_SEATS,0) - GREATEST(0, NVL(SOLD_SEATS,0) - v_qty)
                               ),
             UPDATED_AT      = SYSTIMESTAMP
       WHERE FLIGHT_ID     = :OLD.FLIGHT_ID
         AND SEAT_CATEGORY = :OLD.SEAT_CATEGORY;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END IF;
END;
/

-- PASO 5: CREAR TRG_TICKETS_BI_TIMESTAMPS (establecer CREATED_AT y UPDATED_AT)
CREATE OR REPLACE TRIGGER AEROLINEA4.TRG_TICKETS_BI_TIMESTAMPS
BEFORE INSERT ON AEROLINEA4.TICKETS
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := LOCALTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := LOCALTIMESTAMP;
    END IF;
END;
/

-- PASO 6: CREAR TRG_TICKETS_BU_UPDATED_AT (actualizar UPDATED_AT)
CREATE OR REPLACE TRIGGER AEROLINEA4.TRG_TICKETS_BU_UPDATED_AT
BEFORE UPDATE ON AEROLINEA4.TICKETS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := LOCALTIMESTAMP;
END;
/

-- PASO 7: VERIFICAR QUE TODOS LOS TRIGGERS ESTÉN VÁLIDOS
SELECT 
    trigger_name, 
    status, 
    trigger_type,
    triggering_event
FROM user_triggers 
WHERE table_name = 'TICKETS'
ORDER BY triggering_event, trigger_name;

-- Deberías ver EXACTAMENTE estos 5 triggers (todos ENABLED):
-- TRG_TICKETS_BI_TIMESTAMPS      | ENABLED | BEFORE EACH ROW | INSERT
-- TRG_TICKETS_AI_DECREMENT       | ENABLED | AFTER EACH ROW  | INSERT
-- TRG_TICKETS_BU_UPDATED_AT      | ENABLED | BEFORE EACH ROW | UPDATE
-- TRG_TICKETS_AU_STATUS_RESTORE  | ENABLED | AFTER EACH ROW  | UPDATE
-- TRG_TICKETS_AD_RESTORE         | ENABLED | AFTER EACH ROW  | DELETE

COMMIT;

-- ============================================================================
-- ¡LISTO! Ahora backv6 guardará correctamente en AEROLINEA4
-- ============================================================================

