-- ============================================================================
-- CREAR TODAS LAS SECUENCIAS NECESARIAS PARA AEROLINEA4
-- Ejecutar en DBeaver conectado a AEROLINEA4
-- ============================================================================

-- SECUENCIA 1: Para CLICK_EVENTS (Analytics)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLICK_EVENTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SEQ_CLICK_EVENTS 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
/

-- SECUENCIA 2: Para TICKETS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TICKETS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SEQ_TICKETS 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
/

-- SECUENCIA 3: Para FLIGHTS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FLIGHTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SEQ_FLIGHTS 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
/

-- SECUENCIA 4: Para USERS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SEQ_USERS 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
/

-- SECUENCIA 5: Para CITIES
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CITIES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE SEQ_CITIES 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
/

-- VERIFICAR QUE TODAS LAS SECUENCIAS SE CREARON
SELECT sequence_name, last_number, increment_by
FROM user_sequences
ORDER BY sequence_name;

-- Deberías ver:
-- SEQ_CITIES
-- SEQ_CLICK_EVENTS
-- SEQ_FLIGHTS
-- SEQ_TICKETS
-- SEQ_USERS

COMMIT;

-- ============================================================================
-- ✅ SECUENCIAS CREADAS
-- ============================================================================


