-- Data inicial para pruebas del sistema de gestión de vuelos
-- Ejecutar después de crear las tablas del esquema principal

-- ==================== DATOS BÁSICOS ====================

-- Verificar que tenemos ciudades y aeropuertos
SELECT 'Ciudades disponibles: ' || COUNT(*) FROM CITIES;
SELECT 'Aeropuertos disponibles: ' || COUNT(*) FROM AEROPUERTOS;
SELECT 'Rutas disponibles: ' || COUNT(*) FROM ROUTES;
SELECT 'Aviones disponibles: ' || COUNT(*) FROM AIRCRAFTS;

-- ==================== VUELOS DE PRUEBA ====================

-- Insertar vuelos usando la tabla FLIGHTS_NEW (renombrar después)
-- Vuelo 1: Guatemala -> Miami (directo)
INSERT INTO FLIGHTS_NEW (
    FLIGHT_NUMBER, ROUTE_ID, AIRCRAFT_ID, 
    DEPARTURE_DATE, DEPARTURE_TIME, ARRIVAL_DATE, ARRIVAL_TIME,
    BASE_PRICE, AVAILABLE_SEATS, STATUS, GATE, TERMINAL, CREATED_BY
) VALUES (
    'AE001', 1, 1, 
    DATE '2024-01-15', TIMESTAMP '2024-01-15 08:00:00',
    DATE '2024-01-15', TIMESTAMP '2024-01-15 12:30:00',
    850.00, 180, 'PUBLISHED', 'A1', 'Terminal 1', 1
);

-- Vuelo 2: Miami -> Guatemala (directo)
INSERT INTO FLIGHTS_NEW (
    FLIGHT_NUMBER, ROUTE_ID, AIRCRAFT_ID, 
    DEPARTURE_DATE, DEPARTURE_TIME, ARRIVAL_DATE, ARRIVAL_TIME,
    BASE_PRICE, AVAILABLE_SEATS, STATUS, GATE, TERMINAL, CREATED_BY
) VALUES (
    'AE002', 2, 1, 
    DATE '2024-01-15', TIMESTAMP '2024-01-15 14:00:00',
    DATE '2024-01-15', TIMESTAMP '2024-01-15 18:30:00',
    850.00, 180, 'PUBLISHED', 'B3', 'Terminal 2', 1
);

-- Vuelo 3: Guatemala -> Madrid con escala en Miami
INSERT INTO FLIGHTS_NEW (
    FLIGHT_NUMBER, ROUTE_ID, AIRCRAFT_ID, 
    DEPARTURE_DATE, DEPARTURE_TIME, ARRIVAL_DATE, ARRIVAL_TIME,
    BASE_PRICE, AVAILABLE_SEATS, STATUS, GATE, TERMINAL, CREATED_BY
) VALUES (
    'AE003', 3, 2, 
    DATE '2024-01-16', TIMESTAMP '2024-01-16 10:00:00',
    DATE '2024-01-17', TIMESTAMP '2024-01-17 09:30:00',
    1450.00, 220, 'PUBLISHED', 'A5', 'Terminal 1', 1
);

-- Vuelo 4: Guatemala -> Ciudad de México
INSERT INTO FLIGHTS_NEW (
    FLIGHT_NUMBER, ROUTE_ID, AIRCRAFT_ID, 
    DEPARTURE_DATE, DEPARTURE_TIME, ARRIVAL_DATE, ARRIVAL_TIME,
    BASE_PRICE, AVAILABLE_SEATS, STATUS, GATE, TERMINAL, CREATED_BY
) VALUES (
    'AE004', 4, 1, 
    DATE '2024-01-17', TIMESTAMP '2024-01-17 16:00:00',
    DATE '2024-01-17', TIMESTAMP '2024-01-17 19:15:00',
    650.00, 180, 'PUBLISHED', 'C2', 'Terminal 1', 1
);

-- Vuelo 5: Borrador para mañana (para pruebas de edición)
INSERT INTO FLIGHTS_NEW (
    FLIGHT_NUMBER, ROUTE_ID, AIRCRAFT_ID, 
    DEPARTURE_DATE, DEPARTURE_TIME, ARRIVAL_DATE, ARRIVAL_TIME,
    BASE_PRICE, AVAILABLE_SEATS, STATUS, GATE, TERMINAL, CREATED_BY
) VALUES (
    'AE005', 1, 3, 
    DATE '2024-01-20', TIMESTAMP '2024-01-20 06:00:00',
    DATE '2024-01-20', TIMESTAMP '2024-01-20 10:30:00',
    900.00, 150, 'DRAFT', NULL, NULL, 1
);

-- ==================== ESCALAS PARA VUELOS CON CONEXIONES ====================

-- Escala en Miami para el vuelo AE003 (Guatemala -> Madrid)
INSERT INTO FLIGHT_LEGS (
    FLIGHT_ID, AIRPORT_ID, LEG_ORDER, 
    ARRIVAL_TIME, DEPARTURE_TIME, 
    CONNECTION_TIME_MINUTES, AIRCRAFT_CHANGE
) VALUES (
    3, 2, 1, -- Vuelo AE003, Aeropuerto Miami (suponiendo ID 2)
    TIMESTAMP '2024-01-16 14:30:00', -- Llegada a Miami
    TIMESTAMP '2024-01-16 17:00:00', -- Salida de Miami
    150, 0 -- 2.5 horas de conexión, sin cambio de avión
);

-- ==================== INVENTARIO POR CATEGORÍA ====================

-- Inventario para AE001 (Guatemala -> Miami)
INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (1, 'ECONOMY', 150, 135, 5, 10);

INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (1, 'BUSINESS', 30, 25, 2, 3);

-- Inventario para AE002 (Miami -> Guatemala)
INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (2, 'ECONOMY', 150, 140, 3, 7);

INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (2, 'BUSINESS', 30, 28, 1, 1);

-- Inventario para AE003 (Guatemala -> Madrid)
INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (3, 'ECONOMY', 180, 165, 8, 7);

INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (3, 'BUSINESS', 40, 35, 3, 2);

-- Inventario para AE004 (Guatemala -> Ciudad de México)
INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (4, 'ECONOMY', 150, 142, 4, 4);

INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (4, 'BUSINESS', 30, 29, 0, 1);

-- Inventario para AE005 (Borrador)
INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (5, 'ECONOMY', 120, 120, 0, 0);

INSERT INTO FLIGHT_INVENTORY (FLIGHT_ID, SEAT_CATEGORY, TOTAL_SEATS, AVAILABLE_SEATS, RESERVED_SEATS, SOLD_SEATS)
VALUES (5, 'BUSINESS', 30, 30, 0, 0);

-- ==================== PRECIOS POR CATEGORÍA ====================

-- Precios para AE001 (Guatemala -> Miami)
INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (1, 'ECONOMY', 850.00, 120.00, 45.00, 1015.00, 1, 1, 75.00);

INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (1, 'BUSINESS', 1850.00, 220.00, 45.00, 2115.00, 1, 1, 0.00);

-- Precios para AE002 (Miami -> Guatemala)
INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (2, 'ECONOMY', 850.00, 120.00, 45.00, 1015.00, 1, 1, 75.00);

INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (2, 'BUSINESS', 1850.00, 220.00, 45.00, 2115.00, 1, 1, 0.00);

-- Precios para AE003 (Guatemala -> Madrid) - Con promoción en Economy
INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, PROMOTIONAL_PRICE, PROMOTION_VALID_UNTIL, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (3, 'ECONOMY', 1450.00, 280.00, 75.00, 1805.00, 1299.00, TIMESTAMP '2024-01-20 23:59:59', 1, 1, 150.00);

INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (3, 'BUSINESS', 3200.00, 450.00, 75.00, 3725.00, 1, 1, 0.00);

-- Precios para AE004 (Guatemala -> Ciudad de México)
INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (4, 'ECONOMY', 650.00, 85.00, 30.00, 765.00, 1, 1, 50.00);

INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (4, 'BUSINESS', 1350.00, 150.00, 30.00, 1530.00, 1, 1, 0.00);

-- Precios para AE005 (Borrador)
INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (5, 'ECONOMY', 900.00, 125.00, 45.00, 1070.00, 1, 1, 75.00);

INSERT INTO FLIGHT_FARES (FLIGHT_ID, SEAT_CATEGORY, BASE_PRICE, TAXES, FEES, TOTAL_PRICE, REFUNDABLE, CHANGEABLE, CHANGE_FEE)
VALUES (5, 'BUSINESS', 2000.00, 250.00, 45.00, 2295.00, 1, 1, 0.00);

-- ==================== DATOS ADICIONALES ====================

-- Configurar check-in y boarding para vuelos publicados
UPDATE FLIGHTS_NEW SET 
    CHECK_IN_START = DEPARTURE_TIME - INTERVAL '2' HOUR,
    CHECK_IN_END = DEPARTURE_TIME - INTERVAL '45' MINUTE,
    BOARDING_TIME = DEPARTURE_TIME - INTERVAL '30' MINUTE
WHERE STATUS = 'PUBLISHED';

-- Agregar algunos logs de cambios de ejemplo
UPDATE FLIGHTS_NEW SET 
    CHANGE_LOG = '[2024-01-10T10:00:00] Usuario 1: Vuelo creado
[2024-01-10T10:05:00] Usuario 1: Vuelo publicado
[2024-01-12T14:30:00] Usuario 1: Puerta de embarque asignada'
WHERE FLIGHT_NUMBER IN ('AE001', 'AE002');

UPDATE FLIGHTS_NEW SET 
    CHANGE_LOG = '[2024-01-10T15:00:00] Usuario 1: Vuelo creado
[2024-01-10T15:05:00] Usuario 1: Escala en Miami configurada
[2024-01-10T15:10:00] Usuario 1: Vuelo publicado'
WHERE FLIGHT_NUMBER = 'AE003';

-- ==================== VERIFICACIONES ====================

-- Mostrar resumen de vuelos creados
SELECT 
    f.FLIGHT_NUMBER,
    f.STATUS,
    f.DEPARTURE_DATE,
    f.DEPARTURE_TIME,
    f.BASE_PRICE,
    f.AVAILABLE_SEATS,
    f.GATE,
    COUNT(fl.ID_LEG) as ESCALAS
FROM FLIGHTS_NEW f
LEFT JOIN FLIGHT_LEGS fl ON f.ID_FLIGHT = fl.FLIGHT_ID
GROUP BY f.ID_FLIGHT, f.FLIGHT_NUMBER, f.STATUS, f.DEPARTURE_DATE, f.DEPARTURE_TIME, f.BASE_PRICE, f.AVAILABLE_SEATS, f.GATE
ORDER BY f.DEPARTURE_DATE, f.DEPARTURE_TIME;

-- Mostrar inventario por vuelo
SELECT 
    f.FLIGHT_NUMBER,
    fi.SEAT_CATEGORY,
    fi.TOTAL_SEATS,
    fi.AVAILABLE_SEATS,
    fi.RESERVED_SEATS,
    fi.SOLD_SEATS
FROM FLIGHTS_NEW f
JOIN FLIGHT_INVENTORY fi ON f.ID_FLIGHT = fi.FLIGHT_ID
ORDER BY f.FLIGHT_NUMBER, fi.SEAT_CATEGORY;

-- Mostrar precios por vuelo
SELECT 
    f.FLIGHT_NUMBER,
    ff.SEAT_CATEGORY,
    ff.BASE_PRICE,
    ff.TOTAL_PRICE,
    ff.PROMOTIONAL_PRICE,
    CASE WHEN ff.PROMOTIONAL_PRICE IS NOT NULL AND ff.PROMOTION_VALID_UNTIL > SYSDATE 
         THEN 'PROMOCIÓN ACTIVA' 
         ELSE 'PRECIO NORMAL' END as ESTADO_PRECIO
FROM FLIGHTS_NEW f
JOIN FLIGHT_FARES ff ON f.ID_FLIGHT = ff.FLIGHT_ID
ORDER BY f.FLIGHT_NUMBER, ff.SEAT_CATEGORY;

-- Mostrar escalas
SELECT 
    f.FLIGHT_NUMBER,
    fl.LEG_ORDER,
    a.NOMBRE_AEROPUERTO as AEROPUERTO_ESCALA,
    fl.ARRIVAL_TIME,
    fl.DEPARTURE_TIME,
    fl.CONNECTION_TIME_MINUTES || ' minutos' as TIEMPO_CONEXION
FROM FLIGHTS_NEW f
JOIN FLIGHT_LEGS fl ON f.ID_FLIGHT = fl.FLIGHT_ID
JOIN AEROPUERTOS a ON fl.AIRPORT_ID = a.ID_AEROPUERTO
ORDER BY f.FLIGHT_NUMBER, fl.LEG_ORDER;

COMMIT;

-- ==================== INSTRUCCIONES FINALES ====================
/*
Para completar la configuración:

1. Si todo se ve bien, renombrar las tablas:
   DROP TABLE FLIGHTS;
   ALTER TABLE FLIGHTS_NEW RENAME TO FLIGHTS;

2. Actualizar hibernate.cfg.xml para incluir las nuevas entidades:
   - FlightLeg
   - FlightInventory  
   - FlightFare

3. Probar los endpoints desde el frontend o con curl

4. Los vuelos de ejemplo incluyen:
   - Vuelos directos (AE001, AE002, AE004)
   - Vuelo con escala (AE003)
   - Vuelo en borrador para pruebas (AE005)
   - Diferentes categorías y precios
   - Una promoción activa en AE003
   - Inventario realista con reservas y ventas

Endpoints de prueba sugeridos:
- GET /api/admin/flights (listar todos)
- GET /api/admin/flights?status=PUBLISHED (solo publicados)
- GET /api/admin/flights/1 (detalles del vuelo 1)
- PUT /api/admin/flights/5/publish (publicar el borrador)
*/
