-- Script para crear las tablas de páginas informativas configurables
-- Sistema de gestión de contenido para páginas informativas de AeroLinea

-- Tabla principal para páginas informativas
CREATE TABLE INFORMATIVE_PAGES (
    ID_PAGE NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PAGE_KEY VARCHAR2(50) NOT NULL UNIQUE, -- Clave única para identificar la página (ej: 'about', 'services', 'contact')
    TITLE VARCHAR2(200) NOT NULL, -- Título de la página
    SLUG VARCHAR2(100) NOT NULL UNIQUE, -- URL slug (ej: 'acerca-de', 'nuestros-servicios')
    META_DESCRIPTION VARCHAR2(500), -- Meta descripción para SEO
    META_KEYWORDS VARCHAR2(500), -- Meta keywords para SEO
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, -- Si la página está activa
    IS_PUBLIC NUMBER(1) DEFAULT 1 NOT NULL, -- Si es accesible sin autenticación
    SORT_ORDER NUMBER(3) DEFAULT 0, -- Orden de aparición en menús
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY NUMBER(10) NOT NULL,
    UPDATED_BY NUMBER(10),
    CONSTRAINT fk_pages_created_by FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER),
    CONSTRAINT fk_pages_updated_by FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID_USER)
);

-- Tabla para secciones de contenido de cada página
CREATE TABLE PAGE_SECTIONS (
    ID_SECTION NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PAGE_ID NUMBER(10) NOT NULL,
    SECTION_KEY VARCHAR2(50) NOT NULL, -- Clave única dentro de la página (ej: 'hero', 'content', 'features')
    TITLE VARCHAR2(200), -- Título de la sección
    CONTENT CLOB, -- Contenido HTML de la sección
    CONTENT_TYPE VARCHAR2(20) DEFAULT 'HTML' NOT NULL, -- HTML, MARKDOWN, TEXT
    SECTION_ORDER NUMBER(3) DEFAULT 0, -- Orden dentro de la página
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY NUMBER(10) NOT NULL,
    UPDATED_BY NUMBER(10),
    CONSTRAINT fk_sections_page FOREIGN KEY (PAGE_ID) REFERENCES INFORMATIVE_PAGES(ID_PAGE) ON DELETE CASCADE,
    CONSTRAINT fk_sections_created_by FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER),
    CONSTRAINT fk_sections_updated_by FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID_USER),
    CONSTRAINT uk_section_page_key UNIQUE (PAGE_ID, SECTION_KEY)
);

-- Tabla para imágenes y recursos multimedia de las páginas
CREATE TABLE PAGE_MEDIA (
    ID_MEDIA NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PAGE_ID NUMBER(10) NOT NULL,
    SECTION_ID NUMBER(10), -- Opcional: asociar a una sección específica
    MEDIA_TYPE VARCHAR2(20) NOT NULL, -- IMAGE, VIDEO, DOCUMENT
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    ALT_TEXT VARCHAR2(255), -- Texto alternativo para imágenes
    CAPTION VARCHAR2(500), -- Pie de foto
    SORT_ORDER NUMBER(3) DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY NUMBER(10) NOT NULL,
    CONSTRAINT fk_media_page FOREIGN KEY (PAGE_ID) REFERENCES INFORMATIVE_PAGES(ID_PAGE) ON DELETE CASCADE,
    CONSTRAINT fk_media_section FOREIGN KEY (SECTION_ID) REFERENCES PAGE_SECTIONS(ID_SECTION) ON DELETE CASCADE,
    CONSTRAINT fk_media_created_by FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER)
);

-- Tabla para configuraciones globales del sitio
CREATE TABLE SITE_CONFIGURATIONS (
    ID_CONFIG NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONFIG_KEY VARCHAR2(100) NOT NULL UNIQUE, -- Clave de configuración (ej: 'site_title', 'contact_email')
    CONFIG_VALUE CLOB, -- Valor de la configuración
    CONFIG_TYPE VARCHAR2(20) DEFAULT 'TEXT' NOT NULL, -- TEXT, HTML, JSON, NUMBER, BOOLEAN
    DESCRIPTION VARCHAR2(500), -- Descripción de la configuración
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY NUMBER(10) NOT NULL,
    UPDATED_BY NUMBER(10),
    CONSTRAINT fk_config_created_by FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER),
    CONSTRAINT fk_config_updated_by FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID_USER)
);

-- Tabla para menús de navegación
CREATE TABLE NAVIGATION_MENUS (
    ID_MENU NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MENU_NAME VARCHAR2(50) NOT NULL, -- Nombre del menú (ej: 'main', 'footer', 'admin')
    MENU_ITEM_KEY VARCHAR2(50) NOT NULL, -- Clave del elemento del menú
    LABEL VARCHAR2(100) NOT NULL, -- Texto que se muestra en el menú
    URL VARCHAR2(500), -- URL de destino
    PAGE_ID NUMBER(10), -- Referencia a página informativa
    PARENT_ID NUMBER(10), -- Para menús jerárquicos
    ICON VARCHAR2(100), -- Icono (clase CSS o nombre)
    SORT_ORDER NUMBER(3) DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    IS_PUBLIC NUMBER(1) DEFAULT 1 NOT NULL, -- Si es visible para usuarios no autenticados
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY NUMBER(10) NOT NULL,
    UPDATED_BY NUMBER(10),
    CONSTRAINT fk_menu_page FOREIGN KEY (PAGE_ID) REFERENCES INFORMATIVE_PAGES(ID_PAGE),
    CONSTRAINT fk_menu_parent FOREIGN KEY (PARENT_ID) REFERENCES NAVIGATION_MENUS(ID_MENU),
    CONSTRAINT fk_menu_created_by FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER),
    CONSTRAINT fk_menu_updated_by FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID_USER)
);

-- Índices para mejorar rendimiento
CREATE INDEX idx_pages_key ON INFORMATIVE_PAGES(PAGE_KEY);
CREATE INDEX idx_pages_slug ON INFORMATIVE_PAGES(SLUG);
CREATE INDEX idx_pages_active ON INFORMATIVE_PAGES(IS_ACTIVE);
CREATE INDEX idx_sections_page ON PAGE_SECTIONS(PAGE_ID);
CREATE INDEX idx_sections_order ON PAGE_SECTIONS(PAGE_ID, SECTION_ORDER);
CREATE INDEX idx_media_page ON PAGE_MEDIA(PAGE_ID);
CREATE INDEX idx_config_key ON SITE_CONFIGURATIONS(CONFIG_KEY);
CREATE INDEX idx_menu_name ON NAVIGATION_MENUS(MENU_NAME);
CREATE INDEX idx_menu_order ON NAVIGATION_MENUS(MENU_NAME, SORT_ORDER);

-- Comentarios para documentación
COMMENT ON TABLE INFORMATIVE_PAGES IS 'Páginas informativas configurables del sitio web';
COMMENT ON TABLE PAGE_SECTIONS IS 'Secciones de contenido de cada página informativa';
COMMENT ON TABLE PAGE_MEDIA IS 'Recursos multimedia asociados a páginas y secciones';
COMMENT ON TABLE SITE_CONFIGURATIONS IS 'Configuraciones globales del sitio web';
COMMENT ON TABLE NAVIGATION_MENUS IS 'Elementos de menús de navegación del sitio';

-- Datos iniciales para páginas informativas específicas de aerolínea
INSERT INTO INFORMATIVE_PAGES (PAGE_KEY, TITLE, SLUG, META_DESCRIPTION, META_KEYWORDS, CREATED_BY) VALUES 
('seat-types', 'Tipos de Asientos', 'tipos-de-asientos', 'Conoce los diferentes tipos de asientos disponibles en nuestros vuelos: Economy, Business y Premium', 'asientos, economy, business, premium, aerolínea, vuelos', 1);

INSERT INTO INFORMATIVE_PAGES (PAGE_KEY, TITLE, SLUG, META_DESCRIPTION, META_KEYWORDS, CREATED_BY) VALUES 
('boarding-instructions', 'Instrucciones de Abordaje', 'instrucciones-abordaje', 'Guía completa sobre el proceso de abordaje, horarios y requisitos para tu vuelo', 'abordaje, instrucciones, vuelos, aeropuerto, embarque', 1);

INSERT INTO INFORMATIVE_PAGES (PAGE_KEY, TITLE, SLUG, META_DESCRIPTION, META_KEYWORDS, CREATED_BY) VALUES 
('checkin-process', 'Proceso de Check-in', 'proceso-checkin', 'Aprende cómo hacer check-in online, en el aeropuerto y todo lo que necesitas saber', 'check-in, registro, aeropuerto, vuelos, documentación', 1);

INSERT INTO INFORMATIVE_PAGES (PAGE_KEY, TITLE, SLUG, META_DESCRIPTION, META_KEYWORDS, CREATED_BY) VALUES 
('baggage-info', 'Información de Equipaje', 'informacion-equipaje', 'Políticas de equipaje, tamaños permitidos, peso y restricciones de seguridad', 'equipaje, maletas, peso, restricciones, aerolínea', 1);

INSERT INTO INFORMATIVE_PAGES (PAGE_KEY, TITLE, SLUG, META_DESCRIPTION, META_KEYWORDS, CREATED_BY) VALUES 
('travel-tips', 'Consejos de Viaje', 'consejos-viaje', 'Recomendaciones útiles para hacer tu viaje más cómodo y seguro', 'consejos, viaje, aerolínea, recomendaciones, seguridad', 1);

INSERT INTO INFORMATIVE_PAGES (PAGE_KEY, TITLE, SLUG, META_DESCRIPTION, META_KEYWORDS, CREATED_BY) VALUES 
('contact', 'Contacto', 'contacto', 'Ponte en contacto con AeroLinea para cualquier consulta o emergencia', 'contacto, aerolínea, soporte, emergencias', 1);

-- Configuraciones iniciales del sitio
INSERT INTO SITE_CONFIGURATIONS (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, CREATED_BY) VALUES 
('site_title', 'AeroLinea - Seguros Aeronáuticos', 'TEXT', 'Título principal del sitio web', 1);

INSERT INTO SITE_CONFIGURATIONS (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, CREATED_BY) VALUES 
('site_description', 'Tu compañía de seguros aeronáuticos de confianza. Protección total para tus vuelos nacionales e internacionales.', 'TEXT', 'Descripción principal del sitio', 1);

INSERT INTO SITE_CONFIGURATIONS (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, CREATED_BY) VALUES 
('contact_email', 'info@aerolinea.com', 'TEXT', 'Email principal de contacto', 1);

INSERT INTO SITE_CONFIGURATIONS (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, CREATED_BY) VALUES 
('contact_phone', '+502 1234-5678', 'TEXT', 'Teléfono principal de contacto', 1);

INSERT INTO SITE_CONFIGURATIONS (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION, CREATED_BY) VALUES 
('contact_address', 'Aeropuerto La Aurora, Zona 13, Ciudad de Guatemala', 'TEXT', 'Dirección principal de la empresa', 1);

-- Menú principal de navegación
INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, SORT_ORDER, CREATED_BY) VALUES 
('main', 'home', 'Inicio', '/home', 1, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, SORT_ORDER, CREATED_BY) VALUES 
('main', 'flights', 'Vuelos', '/flights', 2, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('main', 'seat-types', 'Asientos', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'seat-types'), 3, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('main', 'checkin-process', 'Check-in', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'checkin-process'), 4, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('main', 'boarding-instructions', 'Abordaje', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'boarding-instructions'), 5, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('main', 'contact', 'Contacto', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'contact'), 6, 1);

-- Menú del footer
INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('footer', 'seat-types', 'Tipos de Asientos', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'seat-types'), 1, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('footer', 'checkin-process', 'Check-in', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'checkin-process'), 2, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('footer', 'boarding-instructions', 'Abordaje', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'boarding-instructions'), 3, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('footer', 'baggage-info', 'Equipaje', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'baggage-info'), 4, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('footer', 'travel-tips', 'Consejos de Viaje', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'travel-tips'), 5, 1);

INSERT INTO NAVIGATION_MENUS (MENU_NAME, MENU_ITEM_KEY, LABEL, URL, PAGE_ID, SORT_ORDER, CREATED_BY) VALUES 
('footer', 'contact', 'Contacto', NULL, (SELECT ID_PAGE FROM INFORMATIVE_PAGES WHERE PAGE_KEY = 'contact'), 6, 1);

COMMIT;
